### ISSUE TITLE
The owner of a reply cannot like/dislike his own reply

### ISSUE THREAD

**Issue by irinafrazao** [Alex44711/SOEN-341-UB3#100]
the owner of a reply shouldnt be able to like/dislike own reply.

Task: make sure owner cannot like/dislike reply
Points: 3
Risks: None
Priority: Medium

**Comment by Tripe2000** [comment]
made it so that the owner can only like his reply once (otherwise its a little sad if he gets zero likes, so we let him have one)

**Comment by irinafrazao** [comment]
In the last sprint meeting, the customer didnt want the owner of a reply to be able to like/dislike his own.
