### ISSUE TITLE
Display title and content of a question on the question page.

### ISSUE THREAD

**Issue by irinafrazao** [Alex44711/SOEN-341-UB3#15]
On the question page, the title and content of the question should be shown.

Tasks: Get data from database and display. Different data for each question.
Points: 3
Risks: Lack of time because of midterms.
Priority: Important. Part of main feature of website.

**Comment by ds161833** [comment]
@irinafrazao you mean fetch the question from the database and display it?

**Comment by irinafrazao** [comment]
Yes thats what i mean.
Display question title and content from db

On Feb 9, 2018 3:44 PM, ds161833 <notifications@github.com> wrote:

@irinafrazao<https://github.com/irinafrazao> you mean fetch the question from the database and display it?
