### ISSUE TITLE
As a logged in user, I want to see all the answers I ever answered in my user page.  **special feature**

### ISSUE THREAD

**Issue by tongweiz** [Alex44711/SOEN-341-UB3#23]
List all answers from one specific user.

Tasks: List all questions that has the users reply in it. When they get redirected to question page, scroll page until their reply.
Points: 4 -> 0 (ended up not doing it)
Risks: Not sure how to scroll page by itself.
Priority: Medium

**Comment by irinafrazao** [comment]
Team decided that this issue will not be done.
