### ISSUE TITLE
As a  user or a guest, I want to see the details of a question and its replies.

### ISSUE THREAD

**Issue by irinafrazao** [Alex44711/SOEN-341-UB3#3]
Description: On the QUESTION page, the title and content of a question will be displayed. There will also be an input for other users to write down replies. Those replies will be displayed under the input. Each reply will also have a like and dislike counter that all users can use and an accept/reject button for the owner of the question.  (graphic design located in the wiki)

Tasks: Implement the necessary inputs and text areas.
Points: 5
Risks: Lack of time from developer because of other classes
Priority: Important. Needed before back end logic of this page can be implemented.

**Comment by irinafrazao** [comment]
![question mock up](https://user-images.githubusercontent.com/15928273/35421178-b908c334-020f-11e8-9714-c01c38c9c470.png)

**Comment by ds161833** [comment]
UI Implemented question closed
