### ISSUE TITLE
Help Dmitry with the template

### ISSUE THREAD

**Issue by ds161833** [Alex44711/SOEN-341-UB3#46]
I cannot see the template for some reason and the pages are displayed in default see the attachements for more info
![image](https://user-images.githubusercontent.com/22376976/36010737-0e1c8d94-0d21-11e8-8a4a-ecd20b91a7fa.png)

Priority: High!

**Comment by ds161833** [comment]
These are the reasons for it
![image](https://user-images.githubusercontent.com/22376976/36010776-477c9ce6-0d21-11e8-8267-ddeb35173b45.png)

**Comment by ds161833** [comment]
I guess I also know why, but I wanted to ask you guys anyway

**Comment by irinafrazao** [comment]
Did it had to do with your vendor folder not being in the project?

**Comment by ds161833** [comment]
yeas, this was the reason, I didn't do the procedure on the wiki
