### ISSUE TITLE
Posted time of questions on home page as a bug. Changes when it shouldn't.

### ISSUE THREAD

**Issue by irinafrazao** [Alex44711/SOEN-341-UB3#67]
Wrong posted date appears on the home page for the different questions. I think that replies change the updated date of a question which is wrong

Task: Locate why this problem occurs. Fix it.
Priority: Medium
Points: 2
Risks: None.

**Comment by Tripe2000** [comment]
should the posted date show the time it was posted or the time it was updated? cause if its the time it was posted at, the code should be `Posted on  {{$data->created_at}}`

**Comment by irinafrazao** [comment]
umm it should probably be the created_at time. Im not sure there is actually a bug but all the times looked pretty similar. need to check.
